# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Due to the nature of setting up auth with elasticsearch this will exist in a separate pod,
# even though if you were to actually use this you would want them in the same pod...
#
# Created with podman-5.2.4
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-12-01T18:51:00Z"
  labels:
    app: kibana-pod
  name: kibana-pod
spec:
  containers:
  - args:
    - /usr/local/bin/kibana-docker
    env:
    - name: ELASTICSEARCH_HOSTS
      value: http://elasticsearch:9200
    - name: ELASTICSEARCH_PASSWORD
      value: YC5ZisGFWFdJ9HP4SxfK
    - name: ELASTICSEARCH_USERNAME
      value: kibana_system
    image: docker.elastic.co/kibana/kibana:8.15.2
    name: kibana
    ports:
    - containerPort: 5601
      hostPort: 5601
    securityContext:
      runAsNonRoot: true
