networks:
  test:
    name: "test"

services:
  # Standalone login service. Meant to be used if setting up without a preexisting login service.
  keycloak:
    networks:
      - test
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
    command: start-dev
    restart: always
    depends_on:
      - keycloakdb
    environment:
      - KC_DB=postgres 
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak 
      - KC_DB_USERNAME=keycloak 
      - KC_DB_PASSWORD=password 
      - KC_HOSTNAME=localhost 
      - KC_HOSTNAME_PORT=8080 
      - KC_HOSTNAME_STRICT=false 
      - KC_HOSTNAME_STRICT_HTTPS=false 
      - KC_HTTP_ENABLED=true 
      - KC_PROXY=edge 
      - KC_LOG_LEVEL=info 
      - KC_METRICS_ENABLED=true 
      - KC_HEALTH_ENABLED=true 
      - KEYCLOAK_ADMIN=admin 
      - KEYCLOAK_ADMIN_PASSWORD=admin 

  # Database for keycloak. Uses postgres
  keycloakdb:
    networks:
      - test
    container_name: keycloak-db
    image: postgres:17.2-alpine
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - keycloak-data:/var/lib/postgresql/data

volumes:
  keycloak-data:
    driver: local