networks:
  test:
    name: "test"

services:
  # Standalone login service. Meant to be used if setting up without a preexisting login service.
  keycloak:
    networks:
      - test
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.5
    ports:
      - "8080:8080"
    command: start-dev
    restart: always
    depends_on:
      - keycloakdb
    env_file: ./keycloak/dev.env

  # Database for keycloak. Uses postgres
  keycloakdb:
    networks:
      - test
    container_name: keycloak-db
    image: postgres:17.2-alpine
    env_file: ./keycloak/dev.env
    volumes:
      - keycloak-data:/var/lib/postgresql/data

volumes:
  keycloak-data:
    driver: local